name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  # ----------------------
  # 1️⃣ BUILD JOB
  # ----------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: sudo apt update && sudo apt install -y build-essential

      - name: Make scripts executable
        run: chmod +x cicd/*.sh

      - name: Build project
        run: bash cicd/build.sh

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: matrix-binary
          path: matrix_app


  # ----------------------
  # 2️⃣ TEST JOB
  # ----------------------
  test:
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - uses: actions/checkout@v4

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: matrix-binary

      - name: Make executable
        run: chmod +x matrix_app

      - name: Run tests
        run: bash cicd/test.sh


  # ----------------------
  # 3️⃣ PACKAGE JOB
  # ----------------------
  package:
    runs-on: ubuntu-latest
    needs: test 

    steps:
      - uses: actions/checkout@v4

      - name: Install dpkg tools
        run: sudo apt update && sudo apt install -y dpkg-dev

      - name: Download binary
        uses: actions/download-artifact@v4
        with:
          name: matrix-binary

      - name: Make executable
        run: chmod +x matrix_app

      - name: Build deb package
        run: bash cicd/package.sh

      - name: Upload deb artifact
        uses: actions/upload-artifact@v4
        with:
          name: matrix-deb-package
          path: matrix-app_1.0-1.deb